---
- name: Install kubernetes package
  yum: name={{ item }} state=present
  with_items:
   - kubernetes

- name: Create /etc/kubernetes/config
  template: src=config dest=/etc/kubernetes/config

- name: Create /etc/kubernetes/apiserver
  template: src=apiserver dest=/etc/kubernetes/apiserver
  notify: restart kube-apiserver

- name: Start kube-apiserver Service
  service: name=kube-apiserver state=started enabled=yes

- name: Start kube-controller-manager Service
  service: name=kube-controller-manager state=started enabled=yes

- name: Start kube-scheduler Service
  service: name=kube-scheduler state=started enabled=yes
