#!usr/bin/python

master_ip = "$master_ip"
nodes_ip_list = "$nodes_ip_list".split(',')

f = open('/etc/ansible/hosts', 'w')

f.write("[masters]\n")
f.write("%s\n\n" % (master_ip))
f.write("[nodes]\n")

for node_ip in nodes_ip_list:
    f.write("%s\n" % (node_ip))

f.close()

