heat_template_version: 2013-05-23

parameters:
  network_id:
    type: string
    label: Network ID
  image_id:
    type: string
    label: Glance Image ID
  flavor:
    type: string
    label: Flavor
  key_name:
    type: string
    label: Key Name
  key:
    type: string
    label: Key Name
  ansible_key:
    type: string
    label: Key Name
  master_ip:
    type: string

resources:
  node_cloud_user:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ungrouped
      config:
        str_replace:
          template: { get_file: 'user-data' }
          params:
            $master_ip: { get_param: master_ip }
            $ip: { get_attr: [port, fixed_ips, 0, ip_address] }
            $ssh_key_1: { get_param: key }
            $ssh_key_2: { get_param: ansible_key }
  
  node_init:
    type: OS::Heat::MultipartMime
    properties:
      parts:
        - config: {get_resource: node_cloud_user }

  port:
    type: OS::Neutron::Port
    properties:
      admin_state_up: true
      network_id: { get_param: network_id }
  instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: port }
      config_drive: True
      user_data_format: RAW
      user_data: { get_resource: node_init }

outputs:
  ip_list:
    description: The IP addresses of the deployed instance
    value: { get_attr: [port, fixed_ips, 0, ip_address] }
  name_list:
    description: The name of the deployed instance
    value: { get_attr: [instance, name] }
