---
- name: Masters installation
  hosts: master
  remote_user: cloud
  become: yes
  become_method: sudo

  roles:
    - kubernetes
    - etcd
    - flannel

- name: Nodes installation
  hosts: nodes
  remote_user: cloud
  become: yes
  become_method: sudo

  roles:
    - kubelet
    - flannel
    - docker

