---
- hosts: all
  gather_facts: false
  tasks:
    - name: Get hostname
      command: hostnamectl --static
      register: hostname

- name: Masters installation
  hosts: master
  remote_user: cloud
  become: yes
  become_method: sudo

  roles:
    - hosts
    - kubernetes
    - etcd
    - flannel

- name: Nodes installation
  hosts: nodes
  remote_user: cloud
  become: yes
  become_method: sudo

  roles:
    - kubelet
    - flannel
    - docker

