---
- name: Install etcd package
  yum: name={{ item }} state=present
  with_items:
   - etcd

- name: Create /etc/etcd/etcd.conf
  template: src=etcd.conf dest=/etc/etcd/etcd.conf
  notify: restart etcd

- name: Start etcd Service
  service: name=etcd state=started enabled=yes
